export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST';
export const GET_PIZZAS_FAILURE = 'GET_PIZZAS_FAILURE';
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS';

export const DELETE_PIZZA_REQUEST = 'DELETE_PIZZA_REQUEST';
export const DELETE_PIZZA_FAILURE = 'DELETE_PIZZA_FAILURE';
export const DELETE_PIZZA_SUCCESS = 'DELETE_PIZZA_SUCCESS';
